name = "kernel"

[people]
leads = [
    "fslongjin",
]

members = [
    "fslongjin",
    "Jomocool",
    "xiaolin2004",
    "1037827920",
    "val213",
    "TTaq",
    "Samuka007",
    "kkkkkong",
    "laokengwt",
]

# 标记已经退休的人
alumni = []

[permissions]


[[github]]
orgs = ["DragonOS-Community"]

